(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph




(* The format of files is compatible with the files generated by:
   https://algorithms.discrete.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)

val export: path -> string graph -> unit

(* graph_results gr returns a graph showing the results 
   gr is the flow graph resulting from the ford fulkerson algorithm *)
val graph_results: (int*int) graph -> (int*int) graph

(* write_results path gr writes in the path file the results
   gr is the flow graph resulting from the ford fulkerson algorithm *)
val write_results: path -> (int*int) graph -> unit
